# Generated by Django 5.0.2 on 2024-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapplication',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
