# Generated by Django 5.0.2 on 2024-02-12 10:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0003_alter_desktopapplication_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopapplication',
            name='apk',
            field=models.FileField(upload_to='TAK_KNISHIP_DEVS/apks/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='TAK/TAK_KNISHIP_DEVS/gallery_images'),
        ),
        migrations.AlterField(
            model_name='mobileapplication',
            name='apk',
            field=models.FileField(upload_to='TAK_KNISHIP_DEVS/apks/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='TAK/TAK_KNISHIP_DEVS/project_images'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='TAK/TAK_KNISHIP_DEVS/team_images'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='TAK/TAK_KNISHIP_DEVS/testimonial_images'),
        ),
    ]
