# Generated by Django 5.0.2 on 2024-02-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
