# Generated by Django 5.0.2 on 2024-02-23 09:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo',
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='TAK/TAK_KNISHIP_DEVS/gallery_images')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tak_devs_app.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(related_name='gallery_images', to='tak_devs_app.galleryimage'),
        ),
    ]
