# Generated by Django 5.0.2 on 2024-02-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0008_remove_gallery_images_gallery_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='photo',
            new_name='image',
        ),
    ]
