# Generated by Django 5.0.2 on 2024-02-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0009_rename_photo_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktopapplication',
            old_name='url',
            new_name='apk_url',
        ),
        migrations.RenameField(
            model_name='mobileapplication',
            old_name='url',
            new_name='apk_url',
        ),
        migrations.RemoveField(
            model_name='desktopapplication',
            name='apk',
        ),
        migrations.RemoveField(
            model_name='mobileapplication',
            name='apk',
        ),
    ]
