# Generated by Django 5.0.2 on 2024-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0011_techstack_remove_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, null=True, to='tak_devs_app.techstack'),
        ),
    ]
