# Generated by Django 5.0.2 on 2024-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0012_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopapplication',
            name='date_released',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='desktopapplication',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mobileapplication',
            name='date_released',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mobileapplication',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
