# Generated by Django 5.0.2 on 2024-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0013_desktopapplication_date_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopapplication',
            name='download_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mobileapplication',
            name='download_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
