# Generated by Django 5.0.2 on 2024-03-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0015_workexperience_no_of_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='desktop_dev',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='mobile_dev',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='ui_dev',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='web_dev',
            field=models.IntegerField(default=55),
        ),
    ]
