# Generated by Django 5.0.2 on 2024-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0018_contactinfo_instgram_contactinfo_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopapplication',
            name='apk',
            field=models.FileField(null=True, upload_to='Apks/'),
        ),
        migrations.AddField(
            model_name='mobileapplication',
            name='apk',
            field=models.FileField(null=True, upload_to='Apks/'),
        ),
        migrations.AlterField(
            model_name='desktopapplication',
            name='icon',
            field=models.ImageField(upload_to='App_icons/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='mobileapplication',
            name='icon',
            field=models.ImageField(upload_to='App_icons/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_background_image',
            field=models.ImageField(upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_picture',
            field=models.ImageField(upload_to='team_images'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_photo',
            field=models.ImageField(upload_to='testimonial_images'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='icon',
            field=models.ImageField(upload_to='WebApp_Icons/'),
        ),
    ]
