# Generated by Django 5.0.2 on 2024-09-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0019_desktopapplication_apk_mobileapplication_apk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Terms', 'Terms'), ('Policy', 'Policy')], max_length=20)),
                ('description', models.TextField()),
                ('date_published', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tak_devs_app.project')),
            ],
        ),
    ]
