# Generated by Django 5.0.2 on 2024-09-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0020_agreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='type',
            new_name='agreement_type',
        ),
    ]
