# Generated by Django 5.0.2 on 2025-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0022_remove_teammember_skype_teammember_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_published',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Mobile App', 'Mobile App'), ('Web', 'Web'), ('Desktop', 'Desktop')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='contactusmessage',
            index=models.Index(fields=['date_sent'], name='tak_devs_ap_date_se_1b3390_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['type', 'project_category'], name='tak_devs_ap_type_6dae32_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['date_published'], name='tak_devs_ap_date_pu_98eb13_idx'),
        ),
    ]
