# Generated by Django 5.0.2 on 2025-05-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0023_alter_project_date_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='tak_devs_ap_type_6dae32_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='about_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_goals',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_faced',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='quote',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('Mobile App', 'Mobile App'), ('Web Application', 'Web Application'), ('Desktop Application', 'Desktop Application')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, to='tak_devs_app.techstack'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_category'], name='tak_devs_ap_project_8c8e1f_idx'),
        ),
        migrations.AddField(
            model_name='projectclient',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='tak_devs_app.project'),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tak_devs_app.project'),
        ),
    ]
