# Generated by Django 5.0.2 on 2025-05-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0024_projectclient_projectfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_applications', to='tak_devs_app.project'),
        ),
        migrations.AlterField(
            model_name='mobileapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_applications', to='tak_devs_app.project'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_applications', to='tak_devs_app.project'),
        ),
    ]
