# Generated by Django 5.0.2 on 2025-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0025_alter_desktopapplication_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclient',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images/'),
        ),
    ]
