# Generated by Django 5.0.2 on 2025-05-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0026_projectclient_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_background_image',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('image_type', models.CharField(choices=[('background', 'Background Image'), ('about', 'About Image'), ('challenge', 'Challenge Image')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='tak_devs_app.project')),
            ],
            options={
                'indexes': [models.Index(fields=['image_type'], name='tak_devs_ap_image_t_d185b1_idx')],
            },
        ),
    ]
