# Generated by Django 5.0.2 on 2025-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0028_projectimage_caption_projectimage_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
