# Generated by Django 5.0.2 on 2025-05-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0029_alter_teammember_instagram_alter_teammember_twitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['order'], name='tak_devs_ap_order_8c1a96_idx'),
        ),
    ]
