# Generated by Django 5.2.17 on 2026-09-06 13:13

from django.db import migrations, models
from django.utils.text import slugify


def populate_project_slugs(apps, schema_editor):
    Project = apps.get_model('tak_devs_app', 'Project')
    used = set()
    for project in Project.objects.order_by('pk'):
        base = slugify(project.title) or f"project-{project.pk}"
        candidate = base
        suffix = 2
        while candidate in used or Project.objects.exclude(pk=project.pk).filter(slug=candidate).exists():
            candidate = f"{base}-{suffix}"
            suffix += 1
        project.slug = candidate
        project.save(update_fields=['slug'])
        used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('tak_devs_app', '0032_website_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(populate_project_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
